### ISSUE TITLE
bog witch update

### ISSUE THREAD

**Issue by pondwater** [ddormer/valheim-serverside#102]
wondering if we can get an update for this mod, it is not working, no creature spawns, and couldnt chop down a tree

**Comment by byt3c** [comment]
bumping - with nice ask :)

**Comment by loander** [comment]
Can confirm latest game update broke this mod sadly

**Comment by bpage-dev** [comment]
Easy fix, not sure what the odds are of getting it merged @ddormer?
https://github.com/ddormer/valheim-serverside/pull/103

**Comment by ddormer** [comment]
Hi everyone, if the only changes needed to update the mod are just a few method type changes as @bpage-dev suggests, then I'll be happy to build and publish a new version. (Unfortunately both me and @jsza have other commitments taking up most of our time, and as such don't have much energy left for modding Valheim)

@bpage-dev Thanks for the PR, that's a great help!

**Comment by bpage-dev** [comment]
Of course! Happy to help, @ddormer 

Just to be clear, I'm not sure what @pondwater is describing in their original issue description:
> wondering if we can get an update for this mod, it is not working, no creature spawns, and couldnt chop down a tree


What my PR _does_ address is a startup issue for dedicated servers that started happening with the bog witch update, where the server fails to startup altogether and outputs the following error repeatedly:

`10/29/2024 18:33:02: Console: [Error : Unity Log] MissingMethodException: Method not found: Vector2i .ZoneSystem.GetZone(UnityEngine.Vector3) `

I shared my PR in this thread because it's titled "bog witch update" :)

**Comment by pondwater** [comment]
@bpage-dev so as you can tell i am a dumb dumb, i have modified the file in your commit to test, put i am to stupid on how to make the .dll, is there a simple way, but i am off to the google machine in the meantime

**Comment by loander** [comment]
When we could be expecting the update to come out? also thank you for this amazing mod!

**Comment by bpage-dev** [comment]
> @bpage-dev so as you can tell i am a dumb dumb, i have modified the file in your commit to test, put i am to stupid on how to make the .dll, is there a simple way, but i am off to the google machine in the meantime

@pondwater Not stupid! :)
If you modified the file as I did, next you just need to build the project.
If you have the .NET SDK installed you _should_ be able to `Rebuild` the project and then see the output logs tell you where the new .dll got sent to.

And the log you're looking for in the output window looks like this:
`Serverside_Simulations -> [...]\valheim-serverside\bin\Debug\Serverside_Simulations.dll`

If you are running into import errors, you may need to also add the `Environment.props` file as noted in the README.md and/or perhaps get the 4.7.2 framework dev pack.

**Comment by bpage-dev** [comment]
> When we could be expecting the update to come out? also thank you for this amazing mod!
> 
> edit: dont get me wrong as im not expecting a date or exact time when its going to be done, more like if you have predictions it could be up. <3

@loander If you need the fix asap to get your dedicated server running again, you can build locally as pondwater is doing, then should be simple as replacing the existing serverside dll with the new one 👍

**Comment by loander** [comment]
> > When we could be expecting the update to come out? also thank you for this amazing mod!
> > edit: dont get me wrong as im not expecting a date or exact time when its going to be done, more like if you have predictions it could be up. <3
> 
> @loander If you need the fix asap to get your dedicated server running again, you can build locally as pondwater is doing, then should be simple as replacing the existing serverside dll with the new one 👍

never really tried doing any mod compilation but ill try to do that as a temporary fix

**Comment by pondwater** [comment]
can confirm this fix works, server is running and appears to be happy

**Comment by byt3c** [comment]
I don;t have build setup prepared.. a release would be most welcome :)

**Comment by ddormer** [comment]
Thanks for everyone's patience, the latest changes have been released and can be found either [here on GitHub](https://github.com/ddormer/valheim-serverside/releases/tag/1.1.7) or on Nexus Mods.
