### ISSUE TITLE
Valheim Plus autofuel incompatibility

### ISSUE THREAD

**Issue by jsza** [ddormer/valheim-serverside#82]
Valheim Plus's AutoFuel feature doesn't function alongside Serverside Simulations.

**Comment by jsza** [comment]
Pre-release build attached with autofuel fix.

[Serverside_Simulations.zip](https://github.com/ddormer/valheim-serverside/files/7192803/Serverside_Simulations.zip)

**Comment by ddormer** [comment]
Fixed in #80
